### ISSUE TITLE
pip install fails with Unicode decode error

### ISSUE THREAD

**Issue by sureshvv** [benmurden/django-intl-tel-input#4]
Collecting django-intl-tel-input==0.1.1
  Using cached django-intl-tel-input-0.1.1.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-29557ydd/django-intl-tel-input/setup.py", line 5, in <module>
        README = readme.read()
      File "/home/s/appt/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 152: ordinal not in range(128)

**Comment by benmurden** [comment]
Perhaps this is a Python 3 issue. I'll look into it.

**Comment by sureshvv** [comment]
See https://github.com/benmurden/django-intl-tel-input/pull/5
